[package]
name = "VSCode_P1"
version = "0.1.0"
edition = "2021"

[dependencies]
#Client-only
reqwest = { version = "0.12.7", features = ["json"] } #HTTP requests - High Level

#Client-Server
tch = "0.17.0"#Pytorch C++ API(libtorch)
serde = { version = "1.0", features = ["derive"] } #Serialize/Deserialize data
serde_json = "1.0"
log = "0.4"#Logging replace in python
env_logger = "0.11.5"#logging implementation for log

#Server-only
tokio = { version = "1", features = ["full"] } #Asynchronous I/O backed applications
actix-web = "4.9.0"

[[bin]]
name = "client"
path = "src/client.rs"
[[bin]]
name = "server"
path = "src/server.rs"
