[package]
name = "SP_P1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/client.rs"
[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
#Client-only
reqwest = { version = "0.12.7", features = ["json"] } #HTTP requests - High Level
ndarray = { version = "0.16.1",features = ["serde"]}#Array Handling
numpy = "0.21.0"#Python based Numpy C API
ndarray-rand = "0.15"#Randomized array with ndarray
ndarray-npy = "0.9.1"# npy and npz format support for ndarray

#Client-Server
tch = "0.17.0"#Pytorch C++ API(libtorch)
#torch-sys = "0.17.0"
#tch-serde = "0.8.0" #Serialize/Deserialize tch-rs types with serde
serde = { version = "1.0", features = ["derive"] } #Serialize/Deserialize data
serde_json = "1.0"
validator = "0.18.1" # works with serde
log = "0.4"#Logging replace in python
env_logger = "0.11.5"#logging implementation for log

#Server-only
tokio = { version = "1", features = ["full"] } #Asynchronous I/O backed applications
axum = "0.7.6"#Web framework

#Extra
rand = "0.8.5"# Randomnedd functionality
hyper = "1.4.1"#Http library-Low level
kaffe = "0.2.0" #Pytorch for Rust
neuro = "0.1.0" #Deep learning runs on GPU
arrayfire = "3.8.0" #High performance for //el computing
warp = "0.3.7"

#[profile.dev]
#opt-level = 2
#panic = "abort"
#lto = true
#codegen-units = 1
#overflow-checks = false

#[profile.release]
#opt-level = 3
#panic = "abort"
#lto = true
#codegen-units = 1
#overflow-checks = false
